<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <EnablePreviewFeatures>True</EnablePreviewFeatures>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AWSSDK.SQS" Version="4.0.100.5" />
    </ItemGroup>

</Project>